### ISSUE TITLE
Exit status of command 'xcodegen --spec project.yml --project project.xcodeproj' was 1 instead of 0.

### ISSUE THREAD

**Issue by brandtdaniels** [NovatecConsulting/fastlane-plugin-xcodegen#1]
After running `fastlane add_plugin xcodegen` and creating a lane to generate my project:

```
  desc "Generate Xcode project"
  lane :generate do

    xcodegen(spec: "project.yml", project: "project.xcodeproj")

  end
```

I am seeing this when running the lane:
`bundle exec fastlane generate`
```
Exit status of command 'xcodegen --spec project.yml --project project.xcodeproj' was 1 instead of 0.
/Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:460:in `block in replace_bin_path': can't find executable xcodegen for gem xcodegen. xcodegen is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/me/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb:480:in `block in replace_bin_path'
	from /Users/me/.rbenv/versions/2.6.3/bin/xcodegen:23:in `<main>'
```

Is this because I also have xcodegen installed via Homebrew?

**Comment by bdomok** [comment]
Hey @brandtdaniels, did you find a solution for this? I'm facing the same issue currently.

**Comment by robertofrontado** [comment]
I'm facing the same issue here :/

**Comment by rlester** [comment]
+1

**Comment by m-ruhl** [comment]
I cannot reproduce the problem.

What ruby installation and version do you use?

**Comment by robertofrontado** [comment]
It's working for me now, having installed xcodegen gem locally was causing some issues with using it via fastlane, I removed the local version and problem solved
